### ISSUE TITLE
Container fails with a volume read-only mounted to a subdirectory of /data

### ISSUE THREAD

**Issue by stephen-dexda** [pypiserver/pypiserver#341]
I have a K8s secret (containing `htpasswd`) read-only mounted to `/data/auth`.

Because of https://github.com/pypiserver/pypiserver/pull/330 this now causes the container to fail, since https://github.com/pypiserver/pypiserver/blob/master/entrypoint.sh is trying to `chown` all of `/data`.

Should it not be sufficient to `chown /data/packages` in `entrypoint.sh`?

**Comment by mplanchard** [comment]
Thanks for the report!

I didn't catch this in the PR, but I think you're right. Since we're just declaring `/data/packages` as a volume, we should just `chown` that. I'll get a new release out this evening. You can pin to v1.3.2 in the meantime if needed.

**Comment by stephen-dexda** [comment]
Yep, have done ;) Thanks for the fast response!

**Comment by mplanchard** [comment]
This should be fixed in the current `latest` and `v1.4.1` tags in the Docker Hub, thanks to 75ec4e9. I also went ahead and released a new PyPI version just to keep things consistent, even though there are no python changes. Let me know if you run into any issues!

**Comment by fish-finger** [comment]
Its still not fixed, getting the same issues pypiserver/pypiserver:v1.3.2 is working fine for me, latest is buggered

**Comment by fish-finger** [comment]
Its still not fixed, getting the same issues pypiserver/pypiserver:v1.3.2 is working fine for me, latest is buggered

**Comment by stephen-dexda** [comment]
This is WFM with pypiserver/pypiserver:latest from 8 hours ago (sha256:9968ad438bee722101b0227259e1317689ee57fecca38fee09444329025ef927). @fish-finger are you sure you've pulled the most recent image and you're not using an older "latest"?

**Comment by mplanchard** [comment]
@stephen-dexda glad it's fixed for you! Thanks again for the report. 

@fish-finger could you either try ensuring that you're actually getting `latest` as @stephen-dexda suggested, or check with the `v1.4.1` tag explicitly?

If you're still seeing issues, please provide some more information about what exactly is broken, what tag you're using, how you're invoking the container, etc.

**Comment by fish-finger** [comment]
Hi there, sorry for late reply. In the end I ended up using a custom docker wrapper to mitigate the issues and also align with my own platform architecture (standard OS, permissions configuration) for local development. I did not have the time to work out what the issues were with the default setup but I definitely had could run the earlier version and struggled with the later (v1.4.1).

**Comment by mplanchard** [comment]
No worries! Sorry to hear you’re still having issues. I think this is
probably a different problem than the one first reported in this issue, but
still clearly related to the changes in the Docker container in v1.4.0. I’m
happy to help figure out if we can fix it. If you could share any errors
you’re getting and how you wound up mitigating the problem in your custom
wrapper, it would help me to figure out what’s going on and whether it’s
something we can fix in the base image.

**Comment by fish-finger** [comment]
Its grand, this was a local deployment issue (compose), in production use Helm with the base image so will wait to see if that plays up before wasting anymore of your time. Cheers for the assistance.

**Comment by mplanchard** [comment]
Okay, that works. I'm going to close this issue then, but please feel free to open a new one if you run into any more problems or if you wind up having trouble with that production build!
